### ISSUE TITLE
Make light ring for front camera turn on when enabled.

### ISSUE THREAD

**Issue by TheKrunch** [team178/2016RobotCmdBased#13]
You will need:
`import edu.wpi.first.wpilibj.Relay;`
`import edu.wpi.first.wpilibj.Relay.Value;`
and
`Relay lightRelay;`
and
`lightRelay = new Relay(0);`

Put in the teleop part.

**Comment by TheKrunch** [comment]
So I made a new file for Relays, not sure if I did it correctly. Someone who knows what they are doing should look at it. I added it into TeleOp also so that it happens in teleop. Like I said, not sure if this is right someone should look at it.

**Comment by gisellegk** [comment]
Shruti & I figured it out at the end of the meeting with lots of help from Elizabeth and Fred!!! Right now it turns on when you enable in Teleop mode, but it can be added to other modes as needed.
