### ISSUE TITLE
Fix Joystick Driving

### ISSUE THREAD

**Issue by gisellegk** [team178/2016RobotCmdBased#14]
Right now it does funky stuff, like trying to go forward makes the robot turn right or something

**Comment by TheKrunch** [comment]
It looks like this was solved... not sure if it was tested.

**Comment by gisellegk** [comment]
Not sure if it was worked on at all....but I'm pretty sure it at least wasn't tested today.

**Comment by Elizabeth-Cho** [comment]
This should be solved by tomorrow when we get the new joysticks.

**Comment by barrontim** [comment]
I have them in my car ready to bring over.

Tim

On Saturday, February 20, 2016, Elizabeth Cho notifications@github.com
wrote:

> This should be solved by tomorrow when we get the new joysticks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/team178/2016RobotCmdBased/issues/14#issuecomment-186738582
> .

## 

Tim Barron
Computer Science Teacher
Farmington High School
Farmington Public Schools
E: barront@fpsct.org
W: 860 673 2514 x2320
C:  860 985 7035

Co-Head Coach of Farmington HS FIRST Robotics Competition Team 178
2013 FIRST Woodie Flowers Award Finalist UTC CT Regional

## 

The documents accompanying this fax or e-mail transmission, including any 
attachments, are for the sole use of the intended recipients and MAY 
contain confidential school, health or other information that is legally 
privileged. The authorized recipient of this information is prohibited from 
disclosing this information to any other party unless required or permitted 
to do so by law or regulation. 

If you are NOT the intended recipient you are hereby notified that ANY 
disclosure, copying, or further distribution of the contents of these 
documents is prohibited. If you have received this information via 
facsimile in error, please notify the sender immediately and arrange for 
the return or destruction of these documents. If information is received 
via e-mail and you are not the intended recipient, please contact the 
sender by e-mail immediately and delete/destroy both the original and the 
reply e-mail message.
