### ISSUE TITLE
debug kicker encoder

### ISSUE THREAD

**Issue by gisellegk** [team178/2016RobotCmdBased#17]

**Comment by ericsims** [comment]
Did d4916f3 fix this?

**Comment by gisellegk** [comment]
@ericsims We did not have the chance to test it.

**Comment by gisellegk** [comment]
Will try to debug on Test Bot.

Some info courtesy of @ericsims 

> The encoders on the mini test bot are hall effect encoders. The kicker encoder is an optical encoder. These are mechanically different.
> - A hall effect encoder has a magnet of the end of the shaft. The two hall effect sensor outputs a pulse every time that the magnet passes by them. This generates 4 (i think) pulses per rotation. The minibot's encoders are attached to the motor, so every time the motor spins you get 4 pulses. The output shaft of the motor is geared down by 256:1 and connected to the wheel. This means that it takes 256 turns of the motor for the wheel to spin once. So, the 4 pulses per motor revolution \* 256 motor revolutions per wheel revolutions = 1024 pulses per wheel revolution
> - An optical encoder has a clear disk attached to the shaft. The disk has black lines, like this one. There are two leds on one side and two phototransistors (or other light sensor) on the other side. When the disk spins the black line beaks the path of light between the led and the phototransistor. The number of pulses per revolution is dependent on the number of lines on the encoder. The kicker encoder has 1440 pulses per revolution (citation)
> 
> No mater what technology is used for generating the pulses, optical or hall effect, you get pulses per revolution. In code you count these the same way. See an example here. You can test the code on the minibot, just remember that there is going to be a different relationship between the number of pulses and the actual revolutions of the motor.
