### ISSUE TITLE
Buy stuff we need for lights

### ISSUE THREAD

**Issue by gisellegk** [team178/2016RobotCmdBased#22]
To buy:
- Adafruit Neopixels or any ws2811-controlled RGB LEDs
  Figure out how much length we need
- Arduino

Maybe try AndyMark and/or Amazon

**Comment by anusha2617** [comment]
We got the lights! @gisellegk

**Comment by gisellegk** [comment]
Awesome! I obviously am not at the meeting and I won't be in tomorrow
(driving to Rochester for the thing!!) but I can have Eric bring an arduino
for you guys to use

On Thu, Feb 25, 2016 at 5:41 PM, Anusha Patel notifications@github.com
wrote:

> We got the lights! @gisellegk https://github.com/gisellegk
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/team178/2016RobotCmdBased/issues/22#issuecomment-189016448
> .

## 

Giselle Koo
