### ISSUE TITLE
Write OI Class (Joystick)

### ISSUE THREAD

**Issue by gisellegk** [team178/2016RobotCmdBased#6]
Not sure what the controls currently are... or what they should be

**Comment by Elizabeth-Cho** [comment]
Controls we should have (Adding as we finish coding things):
- [ ] Driving the robot
- [ ] Kicking the boulder
- [ ] Getting the boulder (Deploy/Retract)
- [ ] Robot pulling itself up (Once we know how it works)

**Comment by gisellegk** [comment]
@anusha2617 and Fred (IDK his github handle) implemented the Joystick in the OI class.

Driving the robot is in the Drive Command , and is activated in the TeleOp CommandGroup.
Kicking the boulder is in the Kick Command, and is linked to button 7 in the OI class.

The other two subsystems don't completely exist yet (physically and programatically). 

Now that the basics are here, we should open new issues to specify what else we need to do.
